version: '3.8'

services:
  ms1-usuarios:
    build:
      context: ./ms1-usuarios
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${MS1_DB_USER}:${MS1_DB_PASSWORD}@${DB_VM_IP}:3306/${MS1_DB_NAME}
    restart: unless-stopped

  ms2-catalogo:
    build:
      context: ./ms2-catalogo
    ports:
      - "8002:8082"
    environment:
      - MONGODB_URI=mongodb://${DB_VM_IP}:27017/${MS2_MONGO_DB}
      - SPRING_DATA_MONGODB_URI=mongodb://${DB_VM_IP}:27017/${MS2_MONGO_DB}
      - MONGODB_DATABASE=${MS2_MONGO_DB}
      - SPRING_DATA_MONGODB_DATABASE=${MS2_MONGO_DB}
    restart: unless-stopped

  ms3-pedidos:
    build:
      context: ./ms3-pedidos
    ports:
      - "8001:8000"
    environment:
      # Conexión a base de datos externa (PostgreSQL)
      - DB_HOST=${DB_VM_IP}
      - DB_PORT=5432
      - DB_USER=${MS3_DB_USER}
      - DB_PASSWORD=${MS3_DB_PASSWORD}
      - DB_NAME=${MS3_DB_NAME}
      # URL para consumir MS2 internamente
      - RESTAURANTS_URL=http://ms2-catalogo:8082/api/v1/restaurantes
    restart: unless-stopped
