spring.application.name=cloudEats-catalogo-restaurantes
server.port=8082

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/cloudeats_catalogo}
spring.data.mongodb.database=${MONGODB_DATABASE:cloudeats_catalogo}
