AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear MV Bases de Datos con puertos 8005 (MySQL), 8004 (PostgreSQL), 8006 (MongoDB) y 8080 (Adminer)"

Parameters:
  InstanceName:
    Type: String
    Default: "MV Bases de Datos"
    Description: "Nombre de la instancia a crear"
  AMI:
    Type: String
    Default: "ami-0b33d2f1547e52c78"
    Description: "ID de AMI (Cloud9Ubuntu22-2026-03-24)"

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      Tags:
        - Key: "Name"
          Value: !Ref InstanceName
      ImageId: !Ref AMI
      InstanceType: "t2.micro"
      KeyName: "vockey"
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: "20"

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Puertos para BDs (MySQL 8005, PostgreSQL 8004, MongoDB 8006) y Adminer (8080)"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "8004"
          ToPort: "8006"
          CidrIp: "0.0.0.0/0"

Outputs:
  InstanceId:
    Description: "ID de la instancia EC2"
    Value: !Ref EC2Instance
  InstancePublicIP:
    Description: "IP publica de la instancia"
    Value: !GetAtt EC2Instance.PublicIp
  InstancePrivateIP:
    Description: "IP privada de la instancia (usar en main.js)"
    Value: !GetAtt EC2Instance.PrivateIp
