services:
  mongodb:
    image: mongo:8
    container_name: cloudeats-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  microservicio-2:
    build: .
    container_name: cloudeats-microservicio-2
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/cloudeats_catalogo
      MONGODB_DATABASE: cloudeats_catalogo
    ports:
      - "8006:80"

volumes:
  mongodb_data:
